In [3]:
import numpy as np

In [5]:
np.__version__

'2.2.4'

## Create & Read 

#### 1D Aray 

In [8]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.shape

(5,)

In [12]:
arr1.dtype

dtype('int64')

In [13]:
arr1.ndim

1

In [14]:
arr1.size

5

#### 2D ARRAY 

In [21]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape # (row, col)

(2, 3)

In [24]:
arr2.dtype    

dtype('int64')

In [25]:
arr2.size

6

### 3D ARRAY

In [43]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])

In [44]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [45]:
arr3.ndim

3

In [46]:
arr3.shape

(3, 2, 3)

## Create Random Away 

In [48]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.55963806, 0.60034234, 0.07725235],
        [0.44318349, 0.65776659, 0.81269752]],

       [[0.43713468, 0.61964755, 0.95366299],
        [0.75592841, 0.2150054 , 0.13376606]],

       [[0.74822897, 0.56814133, 0.19320901],
        [0.1476331 , 0.43881061, 0.9223154 ]]])

In [49]:
randomArr.dtype

dtype('float64')

In [52]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
zeroes.ndim

3

In [55]:
full = np.full((3, 2, 3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [56]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [62]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [64]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [65]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [66]:
arr3[1][0][1]

np.int64(5)

In [67]:
arr3[1, 0, 1]

np.int64(5)

## Update e Delete

In [68]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [69]:
a1

array([[[0.44578894, 0.69789631],
        [0.52238292, 0.74682454],
        [0.03462478, 0.70577332]],

       [[0.08178247, 0.09361289],
        [0.91992979, 0.00239875],
        [0.92935034, 0.01157867]]])

In [74]:
a2

array([[[0.14531872, 0.29616699],
        [0.63307102, 0.56657641],
        [0.42491157, 0.48381542]],

       [[0.65920901, 0.47519188],
        [0.2490041 , 0.44440011],
        [0.90918948, 0.45497198]]])

## Basic Math Operations 

In [75]:
np.add(a1, a2)

array([[[0.59110765, 0.9940633 ],
        [1.15545394, 1.31340095],
        [0.45953635, 1.18958875]],

       [[0.74099148, 0.56880477],
        [1.16893389, 0.44679886],
        [1.83853982, 0.46655065]]])

In [76]:
np.subtract(a1, a2)

array([[[ 0.30047022,  0.40172931],
        [-0.1106881 ,  0.18024813],
        [-0.39028679,  0.2219579 ]],

       [[-0.57742654, -0.38157899],
        [ 0.6709257 , -0.44200136],
        [ 0.02016087, -0.44339331]]])

In [77]:
np.divide(a1, a2)

array([[[3.06766362, 2.35642839],
        [0.82515689, 1.31813561],
        [0.08148702, 1.45876566]],

       [[0.12406152, 0.19700019],
        [3.69443636, 0.00539773],
        [1.02217455, 0.02544919]]])

In [78]:
np.multiply(a1, a2)

array([[[0.06478148, 0.20669385],
        [0.33070549, 0.42313317],
        [0.01471247, 0.34146402]],

       [[0.05391174, 0.04448409],
        [0.22906629, 0.00106601],
        [0.84495555, 0.00526797]]])

### Statical Operations

In [81]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [82]:
sqrt

np.float64(5.0)

In [83]:
abs

np.int64(2)

In [84]:
power

np.int64(256)

In [85]:
log

np.float64(3.2188758248682006)

In [86]:
mins

np.float64(0.0023987520896003867)

In [87]:
maxs

np.float64(0.909189476166777)

### Update

In [89]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [90]:
arr3[0, 0, 2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [91]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [92]:
# Reshape
arr3.shape

(3, 2, 3)

In [96]:
arr3_reshape = arr3.reshape((2, 3, -1))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [97]:
arr3_reshape.shape

(2, 3, 3)

### Appending & Inserting

In [99]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [101]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [102]:
appd = np.append(zeroes, new_array, axis = 0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# Insert

In [103]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [104]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [108]:
inserted_array = np.insert(zeroes, 2, new_array, axis = 0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [109]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.75973004, 0.76837137, 0.53707098],
        [0.33159321, 0.38907533, 0.56938082]],

       [[0.33767177, 0.01913223, 0.59301228],
        [0.54920873, 0.91826616, 0.777576  ]],

       [[0.67332637, 0.44331639, 0.76828433],
        [0.40656179, 0.24139708, 0.25182822]]])

In [112]:
# delete the array
arr5 = np.delete(arr4, 0, axis = 1)

In [113]:
arr5

array([[[0.33159321, 0.38907533, 0.56938082]],

       [[0.54920873, 0.91826616, 0.777576  ]],

       [[0.40656179, 0.24139708, 0.25182822]]])

In [114]:
np.save("new_array", arr5)

In [115]:
np.load("new_array.npy")

array([[[0.33159321, 0.38907533, 0.56938082]],

       [[0.54920873, 0.91826616, 0.777576  ]],

       [[0.40656179, 0.24139708, 0.25182822]]])